package com.example.taskrfrv

data class Restaurent(
    val ISfeature: String,
    val address: String,
    val approved: String,
    val category: List<String>,
    val city: String,
    val created_at: String,
    val details: String,
    val discount: String,
    val distance: String,
    val email: String,
    val endTime: String,
    val fridayTime: String,
    val id: String,
    val image: String,
    val lang: String,
    val lat: String,
    val like: String,
    val minBilling: String,
    val mondayTime: String,
    val orderNumber: String,
    val phone: String,
    val rating: String,
    val saturdayTime: String,
    val startTime: String,
    val statusAvlbl: String,
    val sundayTime: String,
    val tableBooking: String,
    val thursdayTime: String,
    val title: String,
    val tuesdayTime: String,
    val type: List<String>,
    val updated_at: String,
    val websiteUrl: String,
    val wednesdayTime: String
)